version: 2
jobs:
    build:
        working_directory: ~/noclick
        docker:
            - image: python:3.6.0
        steps:
            - checkout
            - setup_remote_docker

            # Installing the Docker Client
            - run:
                name: Install Docker client
                command: |
                    set -x
                    VER="17.03.0-ce"
                    curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
                    tar -xz -C /tmp -f /tmp/docker-$VER.tgz
                    mv /tmp/docker/* /usr/bin

            # Login, Build and Push
            - run: |
                TAG=0.1.$CIRCLE_BUILD_NUM
                cd back-end
                docker build -t  sakshaat/noclick:$TAG . 
            
            # Tests
            - run: |
                echo "Add Tests"

            # Deploy Test (Need to do later)
            # - deploy:
            #     command: |
            #         if [ "${CIRCLE_BRANCH}" == "staging" ]; then 
            #             cd back-end
            #             eb init -r us-east-2 noclick-staging -p Docker
            #             eb deploy -l $CIRCLE_BUILD_NUM 
            #         fi

            # Deploy Production
            - deploy:
                command: |
                    if [ "${CIRCLE_BRANCH}" == "master" ]; then
                        pip install awsebcli
                        cd back-end
                        docker login -u $DOCKER_ID -p $DOCKER_PASSWORD
                        docker push sakshaat/noclick:$TAG
                        eb init -r us-east-2 noclick -p Docker
                        eb deploy -l $CIRCLE_BUILD_NUM 
                    fi

